### ISSUE TITLE
DDPPlugin does not accept find_unused_parameters when used with Lightning CLI

### ISSUE THREAD

**Issue by gau-nernst** [Lightning-AI/lightning#11574]
## 🐛 Bug

Since DDPPlugin does not have type annotation for `find_unused_parameters` in its `__init__()`, Lightning CLI cannot parse the config (or more correctly, `jsonargparse`?). The following will fail:

```yaml
trainer:
  gpus: 2
  strategy:
    class_path: pytorch_lightning.plugins.DDPPlugin
    init_args:
      find_unused_parameters: false
```

I looked at the new `strategies` module, and it seems like it will have the same problem also.

Right now I'm using a workaround as suggested [here](https://github.com/PyTorchLightning/pytorch-lightning/issues/8262)

```yaml
trainer:
  gpus: 2
  strategy: ddp_find_unused_parameters_false
```

### To Reproduce

```python
# train.py
import torch
from torch.utils.data import DataLoader, Dataset

from pytorch_lightning import LightningModule
from pytorch_lightning.utilities.cli import LightningCLI


class RandomDataset(Dataset):
    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return self.len


class BoringModel(LightningModule):
    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)

    def forward(self, x):
        return self.layer(x)

    def training_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("train_loss", loss)
        return {"loss": loss}

    def validation_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("valid_loss", loss)

    def train_dataloader(self):
        return DataLoader(RandomDataset(32, 64), batch_size=2)

    def val_dataloader(self):
        return DataLoader(RandomDataset(32, 64), batch_size=2)

    def configure_optimizers(self):
        return torch.optim.SGD(self.layer.parameters(), lr=0.1)


if __name__ == "__main__":
    cli = LightningCLI(BoringModel)
```

```yaml
# config.yaml
trainer:
  gpus: 2
  strategy:
    class_path: pytorch_lightning.plugins.DDPPlugin
    init_args:
      find_unused_parameters: false
```

```bash
python train.py fit --config config.yaml
```

### Expected behavior

Using `find_unused_parameters: false` should work with Lightning CLI config file. This can probably be fixed by adding `find_unused_parameters: Optional[bool] = True` in DDPPlugin/DDPStrategy `__init__()`?

### Environment

- PyTorch Lightning Version (e.g., 1.5.0): 1.5.9
- PyTorch Version (e.g., 1.10): 1.10.1
- Python version (e.g., 3.9): 3.8
- OS (e.g., Linux): Linux
- CUDA/cuDNN version: 11.3.1 / 8.2.0
- GPU models and configuration: 4x 3090
- How you installed PyTorch (`conda`, `pip`, source): conda
- If compiling from source, the output of `torch.__config__.show()`:
- Any other relevant information:

### Additional context

cc @carmocca @mauvilsa
