### ISSUE TITLE
[CLI] Can not parse --data data.yaml correctly

### ISSUE THREAD

**Issue by m9jiang** [Lightning-AI/lightning#13094]
## 🐛 Bug

Trying to parse trainer, model, and data config from yaml files to CLI with
`python pl_cli.py test --trainer trainer.yaml --model model.yaml --data data.yaml`
While the trainer and models are parsed to CLI correctly, line 342 in pytorch_lightning->utilities->cli.py throws an error when parsing data:
```
Exception has occurred: ValueError       (note: full exception trace is shown but execution is paused at: _run_module_as_main)
Could not generate a config for 'data.yaml' 
```

### To Reproduce
`python pl_cli.py test --trainer trainer.yaml --model model.yaml --data data.yaml`

pl_cli.py
```python
# datasets are registered by @DATAMODULE_REGISTRY
from foo.datasets. import *   
from pytorch_lightning.utilities.cli import LightningCLI


if __name__ == '__main__':
    cli = LightningCLI(save_config_overwrite=True)
```
trainer.yaml

```yaml
logger:
  class_path: pytorch_lightning.loggers.TensorBoardLogger
  init_args:
    save_dir: tensorboard
```
model.yaml
```yaml
class_path: my_model
init_args:
  pretrained: true
```
data.yaml
```yaml
class_path: foo.datasets.my_data
init_args:
  data_dir: data
```

### Expected behavior

Parse data.yaml to PL CLI correctly

### Environment

- PyTorch Lightning Version: 1.6.3
- PyTorch Version: 1.10.1
- Python version: 3.8.12
- OS: Linux
- CUDA/cuDNN version: 10.2

### Additional context

A workaround is to add the key `data` to data.yaml and use `--config` to parse `data.yaml`
`python pl_cli.py test --trainer trainer.yaml --model model.yaml --config data.yaml`

data.yaml
```yaml
data:
  class_path: foo.datasets.my_data
  init_args:
    data_dir: data
```

cc @carmocca @mauvilsa
