### ISSUE TITLE
WandbLogger does not work with LightningCLI

### ISSUE THREAD

**Issue by asaph-marvin** [Lightning-AI/lightning#16496]
### Bug description

I'm trying to use lightningCLI with a WandbLogger but i get this error:
```
main.py [options] fit: error: Parser key "trainer":
Unable to load config 'config/trainer.yaml'
  - Parser key "trainer.logger":
    Does not validate against any of the Union subtypes
    Subtypes: (<class 'pytorch_lightning.loggers.logger.Logger'>, typing.Iterable[pytorch_lightning.loggers.logger.Logger], <class 'bool'>)
    Errors:
      - argument --config: conflicting option string: --config
      - Expected a <class 'collections.abc.Iterable'>
      - Expected a <class 'bool'>
    Given value type: <class 'dict'>
    Given value: {'class_path': 'pytorch_lightning.loggers.WandbLogger', 'init_args': {'project': 'mangrove-segmentation'}}
```

this is my trainer.yaml:
```
logger:
  class_path: pytorch_lightning.loggers.WandbLogger
  init_args:
    project: mangrove-segmentation
```

i'm using `pytorch_lightning==1.7.0` and `wandb==0.13.9`
