### ISSUE TITLE
Add intermediate arguments in LightningCLI

### ISSUE THREAD

**Issue by rusmux** [Lightning-AI/lightning#16894]
### Description & Motivation

I have a base config `base.yaml`:

```Yaml
...
model: model.yaml
data: data.yaml
...
```

In `model.yaml`:

```Yaml
class_path: src.model.module.CustomModule

init_args:
  model:
    num_classes: 12

  criterion:
    num_classes: 12
...
```

I would like to define a top-level variable `num_classes` in `model.yaml` to reference it in other parts. However, I can't do this, as it wouldn't be a valid configuration structure. Maybe add an option that allows one to use variables with a dot prefix in configuration files? For example:

```Yaml
class_path: src.model.module.CustomModule

.num_classes: 12

init_args:
  model:
    num_classes: ${.num_classes}

  criterion:
    num_classes: ${.num_classes}
...
```

I can add an argument to the Lightning parser, but this only works if I keep all the logic in one file.

### Pitch

Create some kind of intermediate arguments.

cc @borda
