### ISSUE TITLE
[Migrate to lightning 2.x]: SLURMEnvironment is not recognized as a ClusterEnviroment

### ISSUE THREAD

**Issue by meshghi** [Lightning-AI/lightning#17781]
### Bug description

I'm trying to disable the auto_requeue on slurm training. Using the guide in [here](https://lightning.ai/docs/pytorch/stable/clouds/cluster_advanced.html), I added my plugin to the trainer, but I get the following error.

`
lightning_fabric.utilities.exceptions.MisconfigurationException: Found invalid type for plugin <lightning.fabric.plugins.environments.slurm.SLURMEnvironment object at 0x2aac895d4640>. Expected one of: PrecisionPlugin, CheckpointIO, ClusterEnviroment, or LayerSync.
`

**Note:** I used to disable the auto_requeue in 1.7.x and 1.8.x with no problem. Now that I'm trying to migrate to 2.x, I get this error.

### What version are you seeing the problem on?

v2.0

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

cc @awaelchli

**Comment by awaelchli** [comment]
Hi @meshghi 
My guess is that you have mixed imports together. As of 2.0, there are two packages: pytorch_lightning (old) and lightning (new). 

So if you import your trainer like this
```py
from pytorch_lightning import Trainer
```
But you import the plugin like this
```py
from lightning.pytorch.plugins.environments import SLURMEnvironment 
```

You are mixing together two independent packages so Lightning will not recognize the type of the other. To fix this, make sure you are using consistently only one package every where. In general, you should update your old import from

```py
import pytorch_lightning as pl
```
to
```py
import lightning.pytorch as pl
```

I hope this helps.

**Comment by meshghi** [comment]
Thank you. That fixed the issue.

**Comment by cbr9** [comment]
Hi @awaelchli. I'm still getting this error with the following Hydra configuration:
```yaml
_target_: lightning.pytorch.Trainer
enable_progress_bar: True
accelerator: gpu
devices: auto
strategy: 
  _target_: lightning.pytorch.strategies.DDPStrategy
  find_unused_parameters: True
precision: 16-mixed
logger:
  _target_: lightning.pytorch.loggers.WandbLogger
plugins:
  - _target_: lightning.pytorch.plugins.environments.SLURMEnvironment
callbacks: 
  - _target_: src.callbacks.history.HistoryWriter
  - _target_: lightning.pytorch.callbacks.ModelCheckpoint
    every_n_epochs: 1
    monitor: ???
  - _target_: lightning.pytorch.callbacks.EarlyStopping
    monitor: ???
    patience: 10
    mode: min
```

and the following sbatch parameters:
```sh
#SBATCH --output=./outputs/slurm.%N.%j.out
#SBATCH --error=./outputs/slurm.%N.%j.err
#SBATCH --partition=shared,sharedp
#SBATCH --nodes=1
#SBATCH --open-mode=append
#SBATCH --requeue
#SBATCH --cpus-per-task=16
#SBATCH --mem=75GB
#SBATCH --signal=SIGUSR1@90
#SBATCH --gres=gpu:4,gpu_mem:30000
#SBATCH --time=03-00:00
#SBATCH --exclude=destc0strapp[12]
```

I made sure to uninstall pytorch_lightning and install lightning, and replace all the old imports with the new ones.
