### ISSUE TITLE
`log_dir` in `Trainer` is wrong for `CSVLogger`

### ISSUE THREAD

**Issue by ioangatop** [Lightning-AI/lightning#18547]
### Bug description

In PyTorch trainer,  the choice of the `log_dir` is the following:
https://github.com/Lightning-AI/lightning/blob/1cee84ca2d8f23ed86fbd9b0a7be8b766d39ea95/src/lightning/pytorch/trainer/trainer.py#L1241-L1245

However, the `CSVLogger` does provide a `log_dir`, which include the experiment name and version (`root`/lightning_logs/version_0) but its `save_dir`, which is chosen as the `log_dir`, returns only the `root`. That raises an error as the training creates the `root` path but not the full `log_dir` where other callbacks like `ModelCheckpoint` try to have access to.

This error however it seems to happen with remove file storage path, like Azure.

### What version are you seeing the problem on?

master

### How to reproduce the bug

Here is the configuration file to reproduce:
```yaml
---
seed_everything: 42
trainer:
  default_root_dir: &OUTPUT_DIR az://<container>@<name>.blob.core.windows.net/experiments
  max_epochs: 10
  logger:
    - class_path: kaiko.ml_framework.loggers.CSVLogger
      init_args:
        save_dir: *OUTPUT_DIR
model:
  class_path: pytorch_lightning.demos.boring_classes.DemoModel
  init_args:
    out_dim: 32
optimizer:
  class_path: torch.optim.Adam
lr_scheduler:
  class_path: torch.optim.lr_scheduler.ConstantLR
data:
  class_path: pytorch_lightning.demos.boring_classes.BoringDataModule
```

### Error messages and logs

```
RuntimeError: Missing folder: az://<container>@<name>.blob.core.windows.net/experiments/lightning_logs/version_0.
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

### More info

The fix is straight forward, as we just need to redirect to log_dir method like the following:
```py3
if len(self.loggers) > 0:
    if not isinstance(self.loggers[0], (TensorBoardLogger, CSVLogger)):
        dirpath = self.loggers[0].save_dir
    else:
        dirpath = self.loggers[0].log_dir
```

cc @borda
